### ISSUE TITLE
Typography Options

### ISSUE THREAD

**Issue by crowecawcaw** [mdbergmann/Eloquent#2]
It would be useful to have a couple more typography options in the display settings, in particular line spacing. I think being able to add more space between lines would make the text a lot more readable and adding space between paragraphs would help break up the sections a little more.

What could be the most useful but perhaps more work would be to have some sort of template system where people could design new layouts for text in different configurations (e.g. custom layouts with or without headings or with or without verse numbers).

**Comment by mdbergmann** [comment]
Yeah, why not. IIRC the line spacing is a hardcoded value right now.

**Comment by mdbergmann** [comment]
Added line and paragraph spacing.

Templating system is indeed more work and will come at a later point.
