### ISSUE TITLE
names of non-english bible books (refences)

### ISSUE THREAD

**Issue by tesscity** [mdbergmann/Eloquent#22]
After upgrade on Sierra changed names of Bible books from my native language czech to english:
- in Bible text
- in right sidebar

When I copy Bible text from eloquent and paste it in any document english names of bible reference stay and I need to manually overwritte to czech...

![01_yosemite](https://cloud.githubusercontent.com/assets/22537926/18982779/ddb59098-86e8-11e6-8f0c-22e20cd08fbf.jpg)
![02_sierra](https://cloud.githubusercontent.com/assets/22537926/18982780/ddb60898-86e8-11e6-892a-85f2bce20ae3.jpg)

**Comment by mdbergmann** [comment]
Same problem with v2.6 on Sierra.

**Comment by mdbergmann** [comment]
Fixed. Released in next beta-2 build.

**Comment by tesscity** [comment]
Thank You. Big Help!
