### ISSUE TITLE
Can not build, The file “Localizable.strings” couldn’t be opened ....

### ISSUE THREAD

**Issue by ctwdtw** [mdbergmann/Eloquent#25]
Hi, thank you for this interesting project. I was searching for free Bible study software on the Internet and found it :) However, after downloaded it and try to use Xcode to build it, I got the following error message:
/Users/someuser/Downloads/Eloquent-master/ru.lproj/Localizable.strings: The file “Localizable.strings” couldn’t be opened because there is no such file. 

What am I suppose to do in order to make it run on my MacBook Pro?
I use: 
macOS Sierra 10.12.2
Xcode Version 8.2.1 (8C1002)

Thank you very much,
Paul

**Comment by DavidHaslam** [comment]
Did you not already try to install the compiled program from [here](https://launchpad.net/eloquent)?

**Comment by mdbergmann** [comment]
A compiled version can be downloaded here: https://github.com/mdbergmann/Eloquent/releases

But I believe ctwdtw actually tried to compile it.

I'll have a look at the missing file.

**Comment by mdbergmann** [comment]
I've pushed the ru.lproj. Please try again if it builds now.
