### ISSUE TITLE
Update README to take account of the eBible.org repo

### ISSUE THREAD

**Issue by DavidHaslam** [mdbergmann/Eloquent#27]
This is way out of date now! "200 texts available in over 50 languages."

Check out the Bible modules repository for eBible.org

**Comment by mdbergmann** [comment]
"200 texts available in over 50 languages."
This is indeed more than 10 years old, taken from the old MacSword program.

I'd be happy to update this all, add a proper Wiki page here with screenshots, etc.

I will try to find the time to make this 2.6 release soon.

**Comment by mdbergmann** [comment]
David, please update the readme if you wish.
The procedure for this is that you create a fork, make your changes and create a pull-request against my repository.

**Comment by DavidHaslam** [comment]
Forking the repo would give the misleading indication that I were an app developer and a Mac user.
I'm neither.

This was merely a friendly observation by a fellow-volunteer for CrossWire.
It's not urgent.

**Comment by mdbergmann** [comment]
No worries.
Do you have a readme text that is better suited? Than I can put it in.

**Comment by DavidHaslam** [comment]
Check this page in the SWORD developers' wiki. 

https://crosswire.org/wiki/Module_Repositories

I do a lot of maintenance on our wiki.

**Comment by mdbergmann** [comment]
eBible.org is now in module manager when synced with the main repo.
