### ISSUE TITLE
Next Chapter

### ISSUE THREAD

**Issue by tru10000** [mdbergmann/Eloquent#29]
Thank you for your excellent work on Eloquent!!

When reading chapter to chapter, clicking the next chapter button advances to the next chapter but the scroll is down to the bottom of the screen. Would it be possible to on advancing to next chapter to also scroll up the text window back up to the top?

**Comment by mdbergmann** [comment]
Hello.

I think that should be possible to do.
I will have a look.

Which version are you using?


Regards

**Comment by tru10000** [comment]
Thanks! I had been using 2.5.1 but just today I downloaded and installed 2.6.0-b5 and both exhibit the same behavior. I appreciate it!

**Comment by mdbergmann** [comment]
OK, thanks.

**Comment by mdbergmann** [comment]
I'd like to release 2.6 final whenever Crosswire released a final version of the API, which is due shortly.
I'd like to put this fix in, too.
If you want, please give this beta version some usage and report any issues.

Thanks,
Manfred

**Comment by tru10000** [comment]
Awesome! Sure, I will use the beta version and report any problems. Thanks for all you're doing for Eloquent!
