### ISSUE TITLE
Mod Options Show Jesus words in red is not working

### ISSUE THREAD

**Issue by ngineerken** [mdbergmann/Eloquent#3]
With the latest 2.5.0/2479 and KJV 2.9 the option is not working to show Jesus word in red

**Comment by mdbergmann** [comment]
You mean the Jesus words are not shown in red in the text?

Manfred

**Comment by ngineerken** [comment]
That is the problem, it worked before updating to the latest SW.

Ken

**Comment by mdbergmann** [comment]
It seems that while converting the generated html to NSAttributedString the <font color/> tag is removed.

**Comment by mdbergmann** [comment]
OK. Got it fixed.
