### ISSUE TITLE
Developer Team?

### ISSUE THREAD

**Issue by githubber** [mdbergmann/Eloquent#31]
Hello!
Hope you are well.

I was trying to build the project from the github repository but I am being asked for a Build Team, and my own personal dev account doesn’t seem to be accepted. Do I need to be added to the github repository somehow?

Please advise,
Shane Cooke

**Comment by mdbergmann** [comment]
Hi.

No, that's unrelated to GitHub.
But I assume you need to setup some Apple developer things.
Like i.e. the BundleId, that is registered by me. You probably have to replace that with one of your own.

**Comment by githubber** [comment]
I see. OK, once I do that how do I send feedback? Through the issues here, or with a Pull request?

**Comment by mdbergmann** [comment]
Depends on what it is.
If it's a bug you'll use the issue tracker here.
If you want some code to be applied you'll create a pull request.
If you want to talk about something the Mailing list might be appropriate.
