### ISSUE TITLE
Can't change module font

### ISSUE THREAD

**Issue by MC1171611** [mdbergmann/Eloquent#33]
When I attempt to change any specific module fonts in Eloquent, it lets me select the changes in the Font panel, but it doesn't update in the Preferences panel, and thus remains with the settings as default. At some point in the past I was able to change it, but for some reason I can no longer do so. 
Eloquent version 2.6.0/2902 on macOS Sierra 10.12.6

**Comment by mdbergmann** [comment]
Yep, that's indeed broken.

**Comment by mdbergmann** [comment]
Fixed.
