### ISSUE TITLE
Words with hyphens aren't highlighted in Search results

### ISSUE THREAD

**Issue by MC1171611** [mdbergmann/Eloquent#36]
![screenshot 2018-03-14 15 50 27](https://user-images.githubusercontent.com/5070011/37424577-9003e7f6-279f-11e8-84e0-4e659c8df140.png)
Normally, search results matching the search term exactly are highlighted in red, but with hyphenated words it doesn't work.

**Comment by DavidHaslam** [comment]
FIO. The module **SpaRV1865** is not yet released by CrossWire.
This screenshot is a from a test build of the module.

**Comment by mdbergmann** [comment]
That's possible. The search highlighting is custom made. Probably not all case are considered.

I'll have a look.

**Comment by mdbergmann** [comment]
Fixed. searches that contain hyphen are now highlighted.
