### ISSUE TITLE
Eloquent doesn't support ShortPromo URL in About section

### ISSUE THREAD

**Issue by MC1171611** [mdbergmann/Eloquent#37]
In a yet-unreleased module that includes a ShortPromo link, Eloquent does not display the URL: 
![screenshot 2018-03-21 14 03 19](https://user-images.githubusercontent.com/5070011/37725040-c8e51286-2d10-11e8-9027-fdade6e84b6f.png)

Xiphos does: 
![screenshot 2018-03-21 16 43 41](https://user-images.githubusercontent.com/5070011/37725083-e8b7ecdc-2d10-11e8-9fd7-f0f226310eea.png)

https://wiki.crosswire.org/DevTools:conf_Files
This would be a useful addition to the About pane. (Thanks to David Haslam for the tip)

**Comment by mdbergmann** [comment]
Now also showing distribution license and promo.
<img width="563" alt="bildschirmfoto 2018-03-26 um 13 24 06" src="https://user-images.githubusercontent.com/2143978/37903673-094a8ebe-30f9-11e8-9347-9439b4d9e348.png">
