### ISSUE TITLE
Why does Eloquent use its own file type for bibles?

### ISSUE THREAD

**Issue by matt-curtis** [mdbergmann/Eloquent#4]
It's not easy to convert to and from, as it's not documented anywhere, to my knowledge. It would be great if Eloquent used a more wide-spread format.

**Comment by mdbergmann** [comment]
I'm not sure I understand your question.
Eloquent uses the format of bibles, commentaries, etc. that are available for SWORD at CrossWire.
The module installer in fact installs official SWORD compatible modules.
In addition to that Eloquent understands folder that have the suffix .swd and contain subfolders with "mods.d" and "modules" as SWORD modules.
If those .swd files are placed into ~/Library/Application Support/Sword/ they are treated as normal SWORD modules.

There is one thing in Eloquent that is incompatible with SWORD modules, that is the notes.
Notes are in fact .rtf files, native to OS X. Those can be opened with TextEdit app for example.
See here more for information about notes:
http://wiki.catug.org/Eloquent#Using_Notes

**Comment by matt-curtis** [comment]
Ah, OK, I think I see. There wiki was a little unclear (or most likely, I just wasn't understanding). I've figured it out, and managed to get my modules imported. Thank you for your work on Eloquent.
