### ISSUE TITLE
Eloquent 2.6.1 crashes on startup -- new installation

### ISSUE THREAD

**Issue by eggertj** [mdbergmann/Eloquent#44]
Trying to upgrade from MacSword to Eloquent.
Moved MacSword and all Sword/MacSword preferences and application support files to trash and emptied trash.  Downloaded Eloquent 4.6.1 zip file and unzipped.  Moved Eloquent.app to /Applications folder.  Ran it, authenticated it, and then it crashes immediately.  Repeated attempts to run it (no authentication needed anymore) also crash.  The crash log indicates it is trying to set up internal modules.

[Eloquent 4.6.1 crashdump.txt](https://github.com/mdbergmann/Eloquent/files/1924702/Eloquent.4.6.1.crashdump.txt)

**Comment by mdbergmann** [comment]
You moved "Application Support/Sword" to trash also?

**Comment by mdbergmann** [comment]
OK, I kind of reproduced it.

**Comment by eggertj** [comment]
Oops, I meant Eloquent 2.6.1 of course.

**Comment by eggertj** [comment]
Yes, I moved Application Support/Sword to the trash also.  I followed the manual uninstallation instructions in the section "Uninstalling MacSword" in this link:
http://www.icanworkthisthing.com/docs/mac_with_voiceover/Eloquent%20formerly%20MacSword%20%20for%20Snowleopard%20and%20Lion%20with%20Voiceover.shtml

**Comment by mdbergmann** [comment]
I need to have a closer look.
Does it help to pull the "Sword" folder from trash?

**Comment by mdbergmann** [comment]
Not all files, only put the old "Sword" folder back to "Application Support".
Delete the prefs, etc.

The crash should only happen if there is an empty Sword folder (or no Sword folder).

**Comment by eggertj** [comment]
Ok, I deleted all the Sword and MacSword files in /Applications, ~/Library/Preferences, and ~/Library/Application Support, except I left the Sword directory in ~/Library/Application Support.  That Sword directory is not empty, it contains the following:
Sword:
	InstallMgr:
		ftp.crosswire.org:
			mods.d:
				2babdict.conf
				ab.conf
				<<many more .conf files>>
			mods.d.tar.gz
			modules:
				texts:
					ztext:
		InstallMgr.conf

Eloquent still crashes immediately on startup.  The crash dump apparently shows the same problem.

**Comment by mdbergmann** [comment]
Weird. Works OK, here, except this Sword folder is empty.

Anyway, I hope I get some time over the weekend to look into it.

**Comment by eggertj** [comment]
I'm not running this as a privileged user (no admin privileges).  Maybe it's a permissions problem?

**Comment by mdbergmann** [comment]
No, no privileged user rights are required.

**Comment by mdbergmann** [comment]
Hi.
Please give 2.6.2-beta1 a try (in releases section).

Manfred

**Comment by eggertj** [comment]
Hi Manfred.
2.6.2-beta1 fixes the startup crash.  Eloquent no longer crashes immediately on startup.

But I can't download any modules.  The Module Manager shows me nine install sources.  If I select Crosswire and refresh install source, I see lots of modules.  If I select ESV2011, setting task to Install, and select process tasks, it acts like it is installing a module (popup window claims so, and some delay occurs).  But the module doesn't show as installed, even on quitting and restarting Eloquent.  Nor does it appear in the Eloquent main window under Biblical Texts.  So I can read only the default module KJV.

After the attempted module installation, I see in the ~/Library/Application Support/Sword directory an InstallMgr directory with nine directories with names that look like date/time stamps.  These probably correspond to the installation sources.  Some of these are empty, probably the sources I didn't refresh.  Some have mods.d subdirectory (with lots of .conf files) and a mods.d.tar.gz file, probably the sources I did refresh.  One also has a modules subdirectory, probably the Crosswire source.  That modules directory contains subdirectories named comments, genbook, lexdict, and texts, each with one subdirectory (zcom, rawgenbook, rawld, and ztext, respectively).  But there are no files in any of these directories under the modules directory.  So it looks like it made a place to install the modules, but didn't actually install them.

When playing around with the module installer, I did get a crash.  Should I start separate issues on GitHub for the module non-loading problem and the module installer problem?

**Comment by eggertj** [comment]
2.6.2-beta2 has resolved the module installation issue.

I had to delete the ~/Library/Application Support/Sword directory, as beta2 didn't like what was an apparently garbled directory left over from beta1.  But with a fresh Sword directory, reinstallation of modules went ok.  Restarting Eloquent after module installation showed that the installed modules were readable.  There was a glitch where changing chapters (command-left or command-right) would update the chapter indication in the pane tab but not the pane contents, but one more restart of Eloquent seems to have resolved that glitch also.

**Comment by mdbergmann** [comment]
I would close this for now.
If it pops up again we'll reopen.
