### ISSUE TITLE
macsword.com is expiring

### ISSUE THREAD

**Issue by nathany** [mdbergmann/Eloquent#51]
macsword.com currently redirects to http://www.eloquent-bible-study.eu/Eloquent_Bible_Study/Eloquent_Bible_Study.html

However, it is expiring next week on March 20th. Did you want to keep this domain or let it go?

**Comment by mdbergmann** [comment]
Is it in your hands?
Would you mind keeping it?

**Comment by nathany** [comment]
Okay. I've transferred it over to CloudFlare, which is a cheaper.

**Comment by mdbergmann** [comment]
Thanks.
Let me know how to compensate by private mail.
