### ISSUE TITLE
Links unter Help gehen ins Leere oder ganz woanders hin

### ISSUE THREAD

**Issue by Berovowilare** [mdbergmann/Eloquent#56]
Hallo Manfred

Die Links im Reiter Help gehen ins Leere oder komplett woanders hin. 

Grüsse

**Comment by mdbergmann** [comment]
OK, Danke.
Der Link fürs Forum geht in der Tat ins Leere.

Der Link für 'Eloquent Home' sollte bald wieder gehen.
Wir haben vor Kurzem die macsword.com domain umgezogen.

Ich lasse das Ticket einstweilen offen.
