### ISSUE TITLE
After CMD-W Eloquent is blocked and I have to Restart it to work again.

### ISSUE THREAD

**Issue by Berovowilare** [mdbergmann/Eloquent#64]
Hallo Manfred

Wenn ich Eloquent mit CMD-W oder über den roten Schliessknopf schliesse, muss ich Eloquent ganz schliessen um es wieder zum Leben zu erwecken. Das hatte ich schon immer mit Eloquent, durch alle Versionen seit ich es installiert habe.

**Comment by mdbergmann** [comment]
Hallo.

CMD-W oder der 'schließ-' Knopf schließt das Fenster.
Aber 'New Workspace' sollte ein neues Fenster öffnen. Zumindest tut es das hier.

**Comment by Berovowilare** [comment]
Hallo

Ja new Workspace geht. Danke.

**Comment by mdbergmann** [comment]
Das ist übrigens für eine dokumenten basierte App auf macOS normal.
Diese Apps beenden sich nicht automatisch wenn das letzte Fenster geschloßen wird, sondern müßen explizit über CMD-Q oder halt Beenden Menu beendet werden.
Ist z.B. bei TextEdit auch so.

**Comment by Berovowilare** [comment]
Was du sagts stimmt schon, aber bei TextEdit kann ich auf das Icon im Dock klicken und es erscheint wieder die Oberfläche, das tut Eloquent nicht. Bei Eloquent habe ich nur die Menüleiste, der Rest der Programmoberfläche fehlt.

**Comment by mdbergmann** [comment]
Du meinst es erstellt sich automatisch wieder ein Fenster bei click im Dock?
Könnte man machen.
Problem ist nur, da es verschiedene Fender gibt, welches sollte geöffnet werden?

**Comment by Berovowilare** [comment]
Ich denke wenn du das bringst, was in General ausgewählt ist. 
Das heisst, ist der Haken bei "Show on Startup" nicht gesetzt, dann ein das was mit Shift-Command-W kommt. 
Und wenn der Haken gesetzt ist, dann das was kommt wenn man Shift-Command-N drückt. 
Ich denke das wär am einfachsten zu Händeln.

Was meinst du?
