### ISSUE TITLE
Cannot launch on Big Sur 11.1

### ISSUE THREAD

**Issue by theaswanson** [mdbergmann/Eloquent#65]
I downloaded release 2.6.5, but I cannot open it on Big Sur (11.1). When launching, I get the following error:

> "Eloquent" can't be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information.

<img width="372" alt="Screen Shot 2021-01-02 at 11 23 07 AM" src="https://user-images.githubusercontent.com/25459801/103461520-f2892880-4cec-11eb-9639-333e1ea8a9f2.png">

**Comment by mdbergmann** [comment]
Always new security requirements from Apple.

Thanks for the heads up.
Stay tuned, I’ll publish an Apple ’notarized’ app soon.


Manfred

**Comment by mdbergmann** [comment]
Please checkout version 2.6.6 available via auto update.


Manfred

**Comment by theaswanson** [comment]
It works now! Thanks for the fix :)
