### ISSUE TITLE
release 2.6.7 is incorrectly signed

### ISSUE THREAD

**Issue by core-code** [mdbergmann/Eloquent#70]
previous releases were properly signed with an 'Developer ID' code-signature, however release 2.6.7 is signed with an incorrect 'Apple Development' signature that is not intended for software distribution:

`Error: downloaded app has different code-signature. EXPECTED Manfred Bergmann (27XS5W9C3J) but FOUND Apple Development: Manfred Bergmann (7FWLEZG9C2)
`

**Comment by mdbergmann** [comment]
Hi.
I realized that my developer membership was expired.
Can you retry?

**Comment by mdbergmann** [comment]
Should be fixed now in build 3091.

**Comment by core-code** [comment]
fully confirmed as resolved. thank you!
